name: BedWars1058-Ratio
version: ${project.version}
author: itz_leoo
main: me.leoo.bedwars.ratio.Main
description: BedWars1058 Ratio stats Addon
depend:
  - PlaceholderAPI
softdepend:
  - BedWars1058
  - BedWarsProxy