name: BedWars1058-Kdr_Fkdr_Wlr
version: 1.1.3
author: itz_leoo
main: me.leoo.bedwars.kd_fkd_wl.Main
description: 'BedWars1058 Kdr, Fkdr and Wlr stats Addon'
depend:
  - PlaceholderAPI
softdepend:
  - BedWars1058
  - BedWarsProxy